### ISSUE TITLE
Ansible Navigator Config File

### ISSUE THREAD

**Issue by tmichett** [tmichett/do374#10]
```
---
ansible-navigator:
  ansible:
    config:
      path: ./ansible.cfg
  execution-environment:
    image: ee-supported-rhel8:latest
    pull:
      policy: missing
  playbook-artifact:
    enable: false
  mode: stdout
```
