### ISSUE TITLE
Update Ansible Navigator Files

### ISSUE THREAD

**Issue by tmichett** [tmichett/do374#3]

**Comment by tmichett** [comment]
---
ansible-navigator:
  ansible:
    config:
      path: ./ansible.cfg
  execution-environment:
    image: ee-supported-rhel8:latest
    pull:
      policy: missing
  playbook-artifact:
    enable: false

**Comment by tmichett** [comment]
```
---
ansible-navigator:
  ansible:
    config:
      path: ./ansible.cfg
  execution-environment:
    image: ee-supported-rhel8:latest
    pull:
      policy: missing
  playbook-artifact:
    enable: false
```
